### ISSUE TITLE
Remove bottom-border on nav bar

### ISSUE THREAD

**Issue by vim-usds** [usds/gatsby-uswds-ts-starter#3]

**Comment by skport** [comment]
Hi, I would like to handle this one,
Do I remove this solid bar, of the image?

<img width="483" alt="is issue this?" src="https://user-images.githubusercontent.com/45557654/210167298-38e9a5bf-2589-4dfe-8c8f-d7ef6f1a5451.png">

**Comment by vim-usds** [comment]
Hello @skport, this is the issue. 

Would love your help on this. This is a new repo so we haven't written up a `CONTRIBUTION.md` yet. In summary;

1. Please name your branches as follows
`skport/3-remove-bottom-border`

2. This repo enforces commit message conventions outlined [here](https://www.conventionalcommits.org/en/v1.0.0/)
3. Please open a PR against main

Thank you for any support
