### ISSUE TITLE
Fix - first nav link always selected

### ISSUE THREAD

**Issue by vim-usds** [usds/gatsby-uswds-ts-starter#6]
When navigating along the navigation links, it seems that the first navigation link is always selected. Looking for clean ways to remove the first link being selected when other links are selected.

**Comment by vim-usds** [comment]
@skport - are you able to look into this one? Totally OK if you are not able to at this time.

**Comment by vim-usds** [comment]
@skport - nvm, I ended up having some time today and took care of it. Thanks for your support.

**Comment by skport** [comment]
@vim-usds 
Good job! Thank you for your continued request.
